# Grilla de colores

Se tiene una grilla de cuadrados de 9×9, cada uno comienza pintado aleatoriamente de rojo o azul. 

<img src="grilla.jpg" width="200">
Se quiere pintar algunos cuadrados de manera que si se divide la grilla total en sub-grillas de 3x3 cada una de estas sub-grillas contenga cuadrados del mismo color pero el color de cada sub-grilla sea diferente que el de las subgrillas adyacentes.
<table>
    <tr>
        <td><img src="grilla-solucion-1.jpg" width="200"></td>
        <td><img src="grilla-solucion-2.jpg" width="200" ></td>
    </tr>
</table>
Resolver el problema de manera que no sea necesario pintar un cuadrado más de una vez y se pinte la cantidad mínima de cuadrados




In [1]:
import numpy as np
solucion1 = np.array([[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],
                      [1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
                      [0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0], 
                     ])
print("Solución 1")
print(solucion1)
solucion2 = np.array([[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
                      [0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],
                      [1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
                     ])
print("Solución 2")
print(solucion2)

Solución 1
[[0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]]
Solución 2
[[1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]]


In [2]:
grilla = np.random.randint(low=0,high=2,size=(9,9))
print(grilla)

[[1 0 0 0 0 1 1 1 1]
 [1 0 1 0 1 1 1 0 0]
 [0 0 0 0 0 0 1 0 1]
 [1 0 1 0 1 1 0 1 0]
 [0 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 0]
 [0 1 0 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 1]
 [1 0 1 1 1 1 0 1 1]]


In [3]:
c_s1 = 0
c_s2 = 0

for x in range(0, grilla.shape[0]):
    
    for y in range(0, grilla.shape[1]):
      
        if grilla[x][y] != solucion1[x][y]:
            c_s1 += 1
        if grilla[x][y] != solucion2[x][y]:
            c_s2 += 1

print("Diferencia con solución 1")
print(c_s1)
print("Diferencia con solución 2")
print(c_s2)
if c_s1 < c_s2:
    print("Se elige la solución 1")
    solucion = solucion1
else:
    solucion = solucion2
    print("Se elige la solución 2")



Diferencia con solución 1
41
Diferencia con solución 2
40
Se elige la solución 2


In [4]:
pintadas = 0
for x in range(0, grilla.shape[0]):
    for y in range(0, grilla.shape[1]):
        if grilla[x][y] != solucion[x][y]:
             grilla[x][y] = solucion[x][y]
             pintadas += 1
print("Cantidad de cuadros pintados: "+str(pintadas))
print(grilla)

Cantidad de cuadros pintados: 40
[[1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]]
