# Grilla de colores

Se tiene una grilla de cuadrados de 9×9, cada uno comienza pintado aleatoriamente de rojo o azul. 

<img src="https://gitlab.com/andrea.navarro/inteligencia-artificial/-/raw/master/heuristica/grilla.jpg" width="200">

Se quiere pintar algunos cuadrados de manera que, si se divide la grilla total en sub-grillas de 3x3, cada una de estas sub-grillas contenga cuadrados del mismo color siendo este diferente que el de las subgrillas adyacentes.

<img src="https://gitlab.com/andrea.navarro/inteligencia-artificial/-/raw/master/heuristica/grilla-solucion-1.jpg" width="200">
<img src="https://gitlab.com/andrea.navarro/inteligencia-artificial/-/raw/master/heuristica/grilla-solucion-2.jpg" width="200" >

Resolver el problema de manera que no sea necesario pintar un cuadrado más de una vez y se pinte la cantidad mínima de cuadrados.




Primero planteamos las dos posibles soluciones.

In [1]:
import numpy as np
solucion1 = np.array([[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],
                      [1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
                      [0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0]
                     ])
solucion2 = np.array([[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],
                      [0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],[0,0,0,1,1,1,0,0,0],
                      [1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,0,0,0,1,1,1]
                     ])

Definimos una grilla de cuadrados de colores donde el color azul se representa con un 1 y el color rojo se representa con 0.

In [2]:
grilla = np.random.randint(low=0,high=2,size=(9,9))
print(grilla)

[[0 0 0 0 1 1 1 0 0]
 [1 1 0 0 0 1 1 0 1]
 [1 1 0 1 1 1 1 1 0]
 [1 1 1 1 1 0 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 1 0 1 0 0 0 0]
 [1 1 1 1 0 0 1 0 0]
 [1 0 1 0 1 0 1 0 0]]


Definimos dos contadores para asimilar a cuál de los modelos planteados anteriores se asemeja la grilla generada.

In [3]:
c_s1 = 0
c_s2 = 0

for x in range(0, grilla.shape[0]):
    for y in range(0, grilla.shape[1]):
        if grilla[x][y] != solucion1[x][y]:
            c_s1 += 1
        if grilla[x][y] != solucion2[x][y]:
            c_s2 += 1

print(f"Cantidad de cuadrados diferentes con la solución 1: {c_s1}")
print(f"Cantidad de cuadrados diferentes con la solución 2: {c_s2}")

Cantidad de cuadrados diferentes con la solución 1: 42
Cantidad de cuadrados diferentes con la solución 2: 39


Elegimos la mejor solucion para pintar los cuadrados y que se asemejen al objetivo original. Nuestra heurística es realizar la menor cantidad de pintadas.

In [6]:
if c_s1 < c_s2:
    print("Se elige la solución 1")
    solucion = solucion1
else:
    solucion = solucion2
    print("Se elige la solución 2")

Se elige la solución 2


In [7]:
pintadas = 0
for x in range(0, grilla.shape[0]):
    for y in range(0, grilla.shape[1]):
        if grilla[x][y] != solucion[x][y]:
             grilla[x][y] = solucion[x][y]
             pintadas += 1
print("Cantidad de cuadros pintados: ", pintadas)
print(grilla)

Cantidad de cuadros pintados:  0
[[1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]]
