## Diseño aerodinámico

Existen cuatro variables que representan valores de parámetros para el diseño de el ala de una aeronave. Cada uno de estos parámetros puede tomar un valor entre 0 y 63.

El modelo aerodinámico dice que la elevación del ala está dada por la formula:

Elevación = (A - B)² + (C - D)² - (A-30)³ - (C-40)³

Encontrar los valores de parámetros que maximicen la elevación del ala.

In [1]:
import numpy
import matplotlib
import matplotlib.pyplot as plt

## Codificación

- Definir como se codificará el problema

Para este problema el cromosoma estará compuesto por 4 genes cada uno de ellos representará un parámetro

[A B C D]

## Adaptación

- Definir como se calculará la adaptación de un individuo
- ¿Existen estados que deben ser penalizados?


In [2]:
def obtener_val_adaptacion(poblacion):
    adaptacion = []
    # Para cada individuo en la población...
    for ind in poblacion:
        adaptacion.append( ( (ind[0]-ind[1])**2 + (ind[2]-ind[3])**2 -(ind[0]-30)**3 - (ind[2]-40)**3) )
    return adaptacion

## Selección

In [3]:
# Recibe la lista con los entrenamientos de cada hijo y los ordena con numeros enteros ej: [1,2,3,4,5,6] basandose en el valor
# que se obtuvo en la adaptacion.
def rank(fitness,population):
    adaptation_function(population)
    array = np.array(fitness)
    temp = array.argsort()
    return (np.arange(len(array))[temp.argsort()]).tolist()
 
 
# Calculamos la probabilidad que tiene cada hijo, basandonos en la "SELECCION BASADA EN RANKING".
def probability(population, fitness):
    probability_list = []
    ranking = rank(fitness, population)
    for i in range(len(population)):
        probability_list.append(
            ((ranking[i]) / sum(ranking))
        )
    return probability_list
 
 
# Seleccionamos el/los padres de la lista de la poblacion, basandonos en la 
# probabilidad de cada individuo.
def select_parents(parents_num, population_len, probability_list):
    # population, weights = probability_list, k = parents_num
    population_aux = range(population_len)
    print(probability_list)
    parent_indexs = np.random.choice(population_aux,size=parents_num, replace=False, p=probability_list)
    return [population[i] for i in parent_indexs]

## Cruza

In [4]:
def crossover(parents):
    parents = np.array(parents)
    childrens = np.empty((len(parents),parents.shape[1]))
    crossover_point = np.uint8(parents.shape[0]/2)
    print(crossover_point)
    for k in range(len(parents)):
        # Índice del primer padre para realizar la cruza
        parent1_idx = k%parents.shape[0]
        # Índice del segundo padre para realizar la cruza
        parent2_idx = (k+1)%parents.shape[0]
        # Generar el primer hijo con la primer mitad de un padre y la segunda de otro
        childrens[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # Generar el segundo hijo con las partes opuestas
        childrens[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    #Devolver lista de hijos
    return childrens

## Mutación

In [5]:
def mutation(childrens):
    for i, children in enumerate(childrens):
        random_index = random.choice(range(4))
        childrens[i][random_index] = round(random.uniform(0,63), 2)
    return childrens

# Algoritmo

In [6]:
#Cantidad de genes
num_genes = 4
#Soluciones por población
sol_per_pop = 10
#Número de padres para cruza
num_parents_mating = 2
#Tamaño de la población
pop_size = (sol_per_pop,num_genes) 
#Crear pobliación inicial con valores aleatorios
new_population = numpy.random.uniform(low=-10000.0, high=10000.0, size=pop_size)
print("Población incial")
print(new_population)
#Cantidad de generaciones a realizar
num_generations = 200

Población incial
[[-7400.67894412 -6913.64271401 -5758.82640777  5490.81632017]
 [ 2572.29013407  6963.98286536  4088.05845047   968.37914646]
 [ 4620.62084297  -615.66420696  -299.61858222 -2763.76583165]
 [ 1517.0949526   -800.05252666  4675.29957227 -1688.24269043]
 [-4541.59482855  1901.57057713 -6392.54562391 -3252.55497635]
 [ 1595.40116277 -5298.02100725  5554.85577468 -9134.05569636]
 [ 4510.06626738  9241.72001587 -2858.1900664   6380.02869179]
 [ 8155.90988503  8862.89187156  4055.93447073  6589.25745498]
 [ 2190.83794551  -997.99408228 -5236.43223791  -650.9399592 ]
 [-3057.56780276 -9517.44472855  9260.32505952  4825.3031159 ]]


In [8]:
gen = []
fit = []
for generation in range(num_generations):
    # Obtener valores de adaptación de la población
    fitness = obtener_val_adaptacion(new_population)
    # Selección
    parents = select_mating_pool(new_population, fitness, num_parents_mating)
    # Cruza
    offspring_crossover = crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0]))

    # Mutación
    offspring_mutation = mutation(offspring_crossover)

    # Crear nueva población basada en los padres y los hijos
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation
       

    # Obtener mejor resultado para la generación
    fit.append(numpy.max(cal_pop_fitness(new_population)))
    gen.append(generation)
    

#Obtener la mejor solución
fitness = cal_pop_fitness(new_population)
best_match_idx = numpy.where(fitness == numpy.max(fitness))
print("Mejor resultado : ", new_population[best_match_idx, :])
print("Adaptación del mejor resultado : ", fitness[best_match_idx[0][0]])


NameError: name 'select_mating_pool' is not defined

In [ ]:

#Gráfico
fig, ax = plt.subplots()
ax.plot(gen, fit, 'b')
ax.set_ylabel('Fitness')
ax.set_xlabel('Generation')
plt.show()