## Diseño aerodinámico

Existen cuatro variables que representan valores de parámetros para el diseño de el ala de una aeronave. Cada uno de estos parámetros puede tomar un valor entre 0 y 63.

El modelo aerodinámico dice que la elevación del ala está dada por la formula:

Elevación = (A - B)² + (C - D)² - (A-30)³ - (C-40)³

Encontrar los valores de parámetros que maximicen la elevación del ala.

In [1]:
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt

## Codificación

- Definir como se codificará el problema

Para este problema el cromosoma estará compuesto por 4 genes cada uno de ellos representará un parámetro

[A B C D]

## Adaptación

- Definir como se calculará la adaptación de un individuo
- ¿Existen estados que deben ser penalizados?

Se calculará el valor de la elevacion en base a los individuos de la poblacion y luego se penalizan o no en base al valor de elevación obtenido por medio de la selección por ranking.


In [2]:
def funcion_adaptacion(poblacion):
    adaptacion = []
    for ind in poblacion:
        adaptacion.append(
            ((ind[0] - ind[1]) ** 2) +
            ((ind[2] - ind[3]) ** 2) -
            ((ind[0] - 30) ** 3) -
            ((ind[2] - 40) ** 3)
        )
    return adaptacion

## Selección

 Ordena los valores de adaptación basándose en el valor que se obtuvo en la función de elevación. Ordena los valores con números enteros. 
 
 Calculamos la probabilidad que tiene cada individuo, basandonos en la "SELECCION BASADA EN RANKING".
 
 Seleccionamos el/los padres para la cruza de la próxima generación, basándonos en la probabilidad de cada individuo.

In [3]:

def rank(adaptacion,poblacion):
    matriz_adaptacion = np.array(adaptacion)
    index = matriz_adaptacion.argsort()
    return (np.arange(len(matriz_adaptacion))[index.argsort()]).tolist()
 
 

def probabilidad_ranking(poblacion, adaptacion):
    probabilidad = []
    ranking = rank(adaptacion, poblacion)
    for i in range(len(poblacion)):
        probabilidad.append(
            ((ranking[i]) / sum(ranking))
        )
    return probabilidad
 
 


def seleccionar_padres(poblacion,adaptacion,cantidad_padres):
    tam_poblacion = len(poblacion)
    probabilidad = probabilidad_ranking(poblacion, adaptacion)        
   
    
    rango = range(tam_poblacion)
   
    indices = np.random.choice(rango,size=cantidad_padres, replace=False, p=probabilidad)
    return [poblacion[i] for i in indices]


## Cruza

In [4]:
def cruzamiento (padres):
    padres = np.array(padres)
    cantidad_padres = padres.shape[0]    
    cantidad_genes = padres.shape[1]
    
    hijos = np.empty((cantidad_padres,cantidad_genes))
    punto_cruza = np.uint8(cantidad_genes%2)
    print(punto_cruza)
    for k in range(cantidad_padres):
        print(k)
        print(cantidad_padres, cantidad_genes)
        # Índice del primer padre para realizar la cruza
        parent1_idx = k%cantidad_padres
        # Índice del segundo padre para realizar la cruza
        parent2_idx = (k+1)%cantidad_padres
        # Generar el primer hijo con la primer mitad de un padre y la segunda de otro
        hijos[k, 0:punto_cruza] = padres[parent1_idx, 0:punto_cruza]
        # Generar el segundo hijo con las partes opuestas
        hijos[k, punto_cruza:] = padres[parent2_idx, punto_cruza:]
        print(parent1_idx,parent2_idx)
        
        print("hijos",hijos)
        
    #Devolver lista de hijos
                
    return hijos
    

## Mutación

# Algoritmo

In [5]:
poblacion = []
cant_individuos = 10

for i in range (cant_individuos):
    
    a = round(random.uniform(0, 63),2)
    b = round(random.uniform(0, 63),2)
    c = round(random.uniform(0, 63),2)
    d = round(random.uniform(0, 63),2)

    poblacion.append([round(a, 2),round(b, 2),round(c, 2),round(d, 2)])


cant_generaciones = 100
cantidad_padres = 2
#ejes del gráfico:

eje_gen = []
eje_adap = []
for generacion in range(cant_generaciones):
    
    adaptacion = funcion_adaptacion(poblacion)
      
    padres = seleccionar_padres(poblacion,adaptacion,cantidad_padres)
   
    
    
    hijos = cruzamiento(padres)
    
    """ #print(childrens)
    childrens = mutation(childrens)
    #print(childrens)
    selected_parents.extend(childrens.tolist())
    new_population = selected_parents
    #print(new_population)
    population_len = len(new_population)
    poblacion = new_population
    
    eje_adap.append(max(fitness))
    eje_gen.append(generacion)"""

0
0
2 4
0 1
hijos [[3.76900000e+001 7.09000000e+000 1.99900000e+001 1.57600000e+001]
 [0.00000000e+000 7.60861095e-321 1.03128995e-311 1.03128995e-311]]
1
2 4
1 0
hijos [[37.69  7.09 19.99 15.76]
 [22.43 54.43 20.37 30.3 ]]
0
0
2 4
0 1
hijos [[37.57 39.55 31.96 53.04]
 [22.43 54.43 20.37 30.3 ]]
1
2 4
1 0
hijos [[37.57 39.55 31.96 53.04]
 [ 4.44 41.35 57.79 47.2 ]]
0
0
2 4
0 1
hijos [[ 4.44 41.35 57.79 47.2 ]
 [37.57 39.55 31.96 53.04]]
1
2 4
1 0
hijos [[ 4.44 41.35 57.79 47.2 ]
 [47.65 62.25 20.45 26.8 ]]
0
0
2 4
0 1
hijos [[ 4.44 41.35 57.79 47.2 ]
 [ 4.44 41.35 57.79 47.2 ]]
1
2 4
1 0
hijos [[ 4.44 41.35 57.79 47.2 ]
 [22.43 54.43 20.37 30.3 ]]
0
0
2 4
0 1
hijos [[36.45 16.72 53.08 14.95]
 [ 4.44 41.35 57.79 47.2 ]]
1
2 4
1 0
hijos [[36.45 16.72 53.08 14.95]
 [ 4.44 41.35 57.79 47.2 ]]
0
0
2 4
0 1
hijos [[39.02 26.19  4.23  1.35]
 [36.45 16.72 53.08 14.95]]
1
2 4
1 0
hijos [[39.02 26.19  4.23  1.35]
 [22.43 54.43 20.37 30.3 ]]
0
0
2 4
0 1
hijos [[39.02 26.19  4.23  1.35]
 [39.02 26.

 [39.02 26.19  4.23  1.35]]
0
0
2 4
0 1
hijos [[47.65 62.25 20.45 26.8 ]
 [ 4.44 41.35 57.79 47.2 ]]
1
2 4
1 0
hijos [[47.65 62.25 20.45 26.8 ]
 [37.69  7.09 19.99 15.76]]
0
0
2 4
0 1
hijos [[22.43 54.43 20.37 30.3 ]
 [47.65 62.25 20.45 26.8 ]]
1
2 4
1 0
hijos [[22.43 54.43 20.37 30.3 ]
 [ 4.44 41.35 57.79 47.2 ]]
0
0
2 4
0 1
hijos [[52.92 22.91 39.25 48.55]
 [22.43 54.43 20.37 30.3 ]]
1
2 4
1 0
hijos [[52.92 22.91 39.25 48.55]
 [28.79 34.01 48.88 27.81]]
0
0
2 4
0 1
hijos [[52.92 22.91 39.25 48.55]
 [52.92 22.91 39.25 48.55]]
1
2 4
1 0
hijos [[52.92 22.91 39.25 48.55]
 [47.65 62.25 20.45 26.8 ]]
0
0
2 4
0 1
hijos [[37.69  7.09 19.99 15.76]
 [52.92 22.91 39.25 48.55]]
1
2 4
1 0
hijos [[37.69  7.09 19.99 15.76]
 [39.02 26.19  4.23  1.35]]
0
0
2 4
0 1
hijos [[52.92 22.91 39.25 48.55]
 [37.69  7.09 19.99 15.76]]
1
2 4
1 0
hijos [[52.92 22.91 39.25 48.55]
 [39.02 26.19  4.23  1.35]]
0
0
2 4
0 1
hijos [[37.57 39.55 31.96 53.04]
 [52.92 22.91 39.25 48.55]]
1
2 4
1 0
hijos [[37.57 39.55 31.96