## Problema del viajante

Resolver el problema del viajante utilizando algoritmos genéticos. 

- ¿Es posible aproximarse al resultado?



### Codificación

- Definir como se codificará el problema


#### Matriz de costos

##### Distancias desde San Rafael

<table>
 <tbody>
  <tr>
   <td></td>
   <td>San Rafael</td>
   <td>El Nihuil</td>
   <td>El sosneado</td>
   <td>Villa Atuel</td>
   <td>Jaime Prats</td>
   <td>Las Malvinas</td>
   <td>Salto de las Rosas</td>
   <td>Rama Caida</td>
   <td>Monte Coman</td>
   <td>Gral. Alvear</td>
   <td>Rincón del Atuel</td>
  </tr>
  <tr>
   <td>San Rafael</td>
   <td>0</td>
   <td>72.7</td>
   <td>137</td>
   <td>55</td>
   <td>74.3</td>
   <td>36.6</td>
   <td>23</td>
   <td>8.7</td>
   <td>54.2</td>
   <td>88.9</td>
   <td>37.6</td>
  </tr>
 </tbody>
</table>

##### Distancias desde otros distritos

<table>
 <tbody>
  <tr>
   <td></td>
   <td>San Rafael</td>
   <td>El Nihuil</td>
   <td>El sosneado</td>
   <td>Villa Atuel</td>
   <td>Jaime Prats</td>
   <td>Las Malvinas</td>
   <td>Salto de las Rosas</td>
   <td>Rama Caida</td>
   <td>Monte Coman</td>
   <td>Gral. Alvear</td>
   <td>Rincón del Atuel</td>
  </tr>
  <tr>
   <td>El Nihuil</td>
   <td>72.5</td>
   <td>0</td>
   <td>108</td>
   <td>120</td>
   <td>135</td>
   <td>97.4</td>
   <td>84</td>
   <td>69.7</td>
   <td>122</td>
   <td>150</td>
   <td>35</td>
  </tr>
  <tr>
   <td>El Sosneado</td>
   <td>137</td>
   <td>108</td>
   <td>0</td>
   <td>184</td>
   <td>199</td>
   <td>162</td>
   <td>148</td>
   <td>134</td>
   <td>186</td>
   <td>214</td>
   <td>99.1</td>
  </tr>
  <tr>
   <td>Villa Atuel</td>
   <td>54.3</td>
   <td>120</td>
   <td>184</td>
   <td>0</td>
   <td>16.7</td>
   <td>45.2</td>
   <td>35.6</td>
   <td>54.5</td>
   <td>47.1</td>
   <td>31.5</td>
   <td>84.7</td>
  </tr>
  <tr>
   <td>Jaime Prats</td>
   <td>70</td>
   <td>136</td>
   <td>200</td>
   <td>16.9</td>
   <td>0</td>
   <td>60.8</td>
   <td>51.3</td>
   <td>70.2</td>
   <td>41.2</td>
   <td>15</td>
   <td>100</td>
  </tr>
  <tr>
   <td>Las Malvinas</td>
   <td>36.6</td>
   <td>97.4</td>
   <td>162</td>
   <td>45.2</td>
   <td>60.8</td>
   <td>0</td>
   <td>18.8</td>
   <td>29.7</td>
   <td>57.8</td>
   <td>75.4</td>
   <td>62.6</td>
  </tr>
  <tr>
   <td>Salto de las Rosas</td>
   <td>23</td>
   <td>84</td>
   <td>148</td>
   <td>35.6</td>
   <td>51.3</td>
   <td>18.8</td>
   <td>0</td>
   <td>18.9</td>
   <td>43</td>
   <td>65.8</td>
   <td>49.1</td>
  </tr>
  <tr>
   <td>Rama Caida</td>
   <td>8.7</td>
   <td>68.7</td>
   <td>134</td>
   <td>54.5</td>
   <td>70.2</td>
   <td>29.2</td>
   <td>18.9</td>
   <td>0</td>
   <td>56.4</td>
   <td>84.7</td>
   <td>34.7</td>
  </tr>
  <tr>
   <td>Monte Coman</td>
   <td>54.2</td>
   <td>122</td>
   <td>186</td>
   <td>47.1</td>
   <td>41.2</td>
   <td>57.8</td>
   <td>43</td>
   <td>56.4</td>
   <td>0</td>
   <td>48</td>
   <td>86.5</td>
  </tr>
  <tr>
   <td>Gral. Alvear</td>
   <td>88.9</td>
   <td>150</td>
   <td>214</td>
   <td>31.5</td>
   <td>15</td>
   <td>75.4</td>
   <td>65.8</td>
   <td>84.7</td>
   <td>48</td>
   <td>0</td>
   <td>115</td>

  </tr>
  <tr>
   <td>Rincón del Atuel</td>
   <td>37.6</td>
   <td>35</td>
   <td>99.1</td>
   <td>84.7</td>
   <td>100</td>
   <td>62.6</td>
   <td>49.1</td>
   <td>34.7</td>
   <td>86.5</td>
   <td>115</td>
   <td>0</td>
  </tr>
 </tbody>
</table>

### Adaptación

- Definir como se calculará la adaptación de un individuo
- ¿Existen estados que deben ser penalizados?


## Resolución

### Objetivo

Recordemos que el objetivo del problema es, dada una lista de ciudades y las distancias entre cada par de ellas, encontrar cuál es la <strong>ruta más corta</strong> posible que visita cada ciudad exactamente una vez y que, al finalizar, regresa a la ciudad origen.

In [11]:
import numpy as np
import random
import copy
import sys
from functools import reduce

# numpy.set_printoptions(threshold=sys.maxsize)

In [2]:
costos = [[0,72.7,136.7,59.1,70.1,36.4,23,8.7,54.2,85.7,37.7],
              [72.7,0,107.8,120.1,135.2,97.7,84.2,69.8,122,150,35],
              [136.7,107.8,0,184,199,162,148,134,186,214,99.1],
              [59.1,120.1,184,0,16.7,45.2,35.6,54.5,47.1,31.4,84.7],
              [70.1, 135.2, 199, 16.7, 0, 60.8, 51.3, 70.2, 41.2, 15, 100],
              [36.4, 97.7, 162, 45.2, 60.8, 0, 18.8, 29.7, 57.8, 75.4, 62.6],
              [23,84.2,148,35.6,51.3,18.8,0,18.9,43,65.8,49.1],
              [8.7,69.8,134,54.5,70.2,29.7,18.9,0,56.4,84.7,34.7],
              [54.2,122,186,47.1,41.2,57.8,43,56.4,0,48,86.5],
              [85.7,150,214,31.4,15,75.4,65.8,84.7,48,0,115],
              [37.6,35,99.1,84.7,100,62.6,49.1,34.7,86.5,115,0]]

costos = np.array(costos)
print("Array costos de distancias: \n")
print(costos)


Array costos de distancias: 

[[  0.   72.7 136.7  59.1  70.1  36.4  23.    8.7  54.2  85.7  37.7]
 [ 72.7   0.  107.8 120.1 135.2  97.7  84.2  69.8 122.  150.   35. ]
 [136.7 107.8   0.  184.  199.  162.  148.  134.  186.  214.   99.1]
 [ 59.1 120.1 184.    0.   16.7  45.2  35.6  54.5  47.1  31.4  84.7]
 [ 70.1 135.2 199.   16.7   0.   60.8  51.3  70.2  41.2  15.  100. ]
 [ 36.4  97.7 162.   45.2  60.8   0.   18.8  29.7  57.8  75.4  62.6]
 [ 23.   84.2 148.   35.6  51.3  18.8   0.   18.9  43.   65.8  49.1]
 [  8.7  69.8 134.   54.5  70.2  29.7  18.9   0.   56.4  84.7  34.7]
 [ 54.2 122.  186.   47.1  41.2  57.8  43.   56.4   0.   48.   86.5]
 [ 85.7 150.  214.   31.4  15.   75.4  65.8  84.7  48.    0.  115. ]
 [ 37.6  35.   99.1  84.7 100.   62.6  49.1  34.7  86.5 115.    0. ]]


### Funcion de adaptación - valores de costos

El valor de costo alto significa baja adapatacion. No podemos usar el valor del costo de la ruta directamente como valor de adaptacion.

In [3]:
def obtener_costo_individuo(individuo_ruta):   
    ultima_localidad = individuo_ruta[0]
    costo_ruta = 0
    
    for localidad_actual in individuo_ruta:
        print(f"Localidad actual {localidad_actual}, última localidad {ultima_localidad}")
        costo_ruta += costos[ultima_localidad][localidad_actual]
        ultima_localidad = localidad_actual
        
# Función de adaptacion - fitness function 
def obtener_adaptacion(poblacion):
    adecuacion = []
    for individuo_ruta in poblacion:
        adecuacion.append(obtener_costo_individuo(individuo_ruta))
    return adecuacion

## Selección

Usamos el metodo de seleccion de ruleta donde los individuos que tengan una probabilidad más alta, van a tener más chances de ser seleccionados, pero no necesariamente.

Cuando los valores de adaptacion estan representados por la lista, lo que nos permite obtener la probabilidad cumulativa que vamos guardando en una lista.

La declaración "lista_prob_acum[-1] = 1,0" compensa los errores de redondeo.

In [4]:
import operator

def obtener_probabilidad(adaptacion):
    sumatoria_adaptacion = reduce(operator.add, adaptacion)
    lista_probabilidad = map((lambda x: x/sumatoria_adaptacion), adaptacion)
    
    prob_acumulada = 0
    lista_prob_acum = []
    for probabilidad in lista_probabilidad:
        lista_prob_acum.append( prob_acumulada + probabilidad )
        prob_acumulada += probabilidad
    lista_prob_acum[-1] = 1.0
    
    return lista_prob_acum

Cuando la lista de probabilidad acumulada es proporcionada (lista_prob_acum), podemos seleccionar cromosomas como se muestra a continuación utilizando la búsqueda secuencial.

Se puede utilizar la búsqueda binaria para un código más rápido. La función random del módulo random devuelve el siguiente número aleatorio de punto flotante en el rango [0.0, 1.0).

In [5]:

def seleccionar_padres(poblacion, adaptacion, cantidad_padres):

    padres_seleccionados = []
    tam_poblacion = len(poblacion)
    
    lista_prob_acum = obtener_probabilidad(adaptacion)
    
    for i in range(tam_poblacion):
        rn = random.random()
        for j, prob_acumulada in enumerate(lista_prob_acum):
            if rn <= cum_prob:
                padres_seleccionados.append(j)
                break 
    return padres_seleccionados

## Cruza

En el caso del problema del viajante, realizamos una cruza por medio de la recombinación de cromosomas ordenados para evitar soluciones inviables.

In [6]:
# TODO: Trabajarlas como funciones

#parent1 = [4, 1, 5, 6, 9, 2, 3, 7, 8]
#parent2 = [3, 1, 8, 6, 2, 4, 7, 9, 5]

#pt1 = 2 # crossover point 1
#pt2 = 5 # crossover point 2

#latter_length = len(parent1) - pt2
#prt1_mid = parent1[pt1:pt2]
#prt2_mid = parent2[pt1:pt2]

#prt1_reordered = parent1[pt2:] + parent1[:pt2]
#prt2_reordered = parent2[pt2:] + parent2[:pt2]

#prt1_reord_filtered = filter( lambda x: x not in prt2_mid, prt1_reordered )
#prt2_reord_filtered = filter( lambda x: x not in prt1_mid, prt2_reordered )

#offspring1 = prt2_reord_filtered[-pt1:] + prt1_mid + prt2_reord_filtered[:latter_length]
#offspring2 = prt1_reord_filtered[-pt1:] + prt2_mid + prt1_reord_filtered[:latter_length]

# The resultant offspring1 and offspring2 are show below.
# [8, 2, 5, 6, 9, 4, 7, 3, 1]
# [5, 9, 8, 6, 2, 3, 7, 4, 1] 

def crossover(parents):
    parents = np.array(parents)
    children = np.empty((len(parents),parents.shape[1]))
    crossover_point = np.uint8(parents.shape[0]/2)
    print(f'Cruza: {crossover_point} \n\n')
    for k in range(len(parents)):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        children[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        children[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return children

## Mutación

El ejemplo de mutación de intercambio se da a continuación. El siguiente código utiliza la asignación paralela. 

In [7]:
#import random

# TODO: Trabajarlas como funciones

#chrm = [4, 1, 5, 6, 9, 2, 3, 7, 8]

# Omitimos la comparación de la posición1 y la posición2 por razones de brevedad pero no deben ser iguales
#position1 = random.randint(0, len(chrm)-1 )
#position2 = random.randint(0, len(chrm)-1 )

#chrm[position1], chrm[position2] = chrm[position2], chrm[position1]

def mutation(chrm):
    for i, child in enumerate(children):
        position1 = random.randint(0, len(chrm)-1 )
        position2 = random.randint(0, len(chrm)-1 )
        chrm[position1], chrm[position2] = chrm[position2], chrm[position1]
    return chrm

# Algoritmo

## Codificación del problema

Para este problema, los individuos (rutas aleatorizadas) estarán compuestos por 10 genes donde cada uno de ellos representará el valor del indice de una localidad en la lista "costos". El mismo será utilizado para trabajar los costos de cada uno de los individuos.

[$L_{1}$, $L_{2}$, $L_{3}$, $L_{4}$, $L_{5}$, $L_{6}$, $L_{7}$, $L_{8}$, $L_{9}$, $L_{10}$]

### Creamos la poblacion inicial

In [12]:
# Elaboramos cromosomas que seran aleatorizados para generar los individuos
crom_ejemplo = list(range(1,11))

poblacion_inicial = [ ]
random.seed(0)
tam_poblacion = 10

for i in range(tam_poblacion):
    crom_nuevo = copy.copy(crom_ejemplo)
    random.shuffle(crom_nuevo)
    poblacion_inicial.append(crom_nuevo)

poblacion_inicial = np.array(poblacion_inicial)

print("\nArray población inicial: ")
print(poblacion_inicial)


best_adaptation = list()
generation = list()
cant_generations = 2 #Generaciones
for i in range(cant_generations):
    fitness = obtener_adaptacion(poblacion_inicial)
    probability_list = obtener_probabilidad(fitness)
    selected_parents = seleccionar_padres(population_len // 2, population_len, probability_list)
    children = crossover(selected_parents)
    children = mutation(childrens)
    selected_parents.extend(childrens.tolist())
    new_population = selected_parents
    population_len = len(new_population)
    population = new_population
    best_adaptation.append(max(fitness))
    generation.append(i)


Array población inicial: 
[[ 8  9  2  6  4  5  3  1 10  7]
 [10  5  9  7  1  2  8  3  4  6]
 [ 8  1 10  4  3  6  7  9  2  5]
 [ 1  3  9  4  2  8  5 10  7  6]
 [ 5  2  3  7  4  6  8 10  9  1]
 [ 9  3  7  5  2  1  8 10  4  6]
 [ 6 10  7  4  5  3  1  2  8  9]
 [ 1  4  6  8  7  3 10  2  5  9]
 [ 6  4  1 10  9  5  3  7  2  8]
 [ 7 10  8  2  6  9  4  5  1  3]]
Localidad actual 8, última localidad 8
Localidad actual 9, última localidad 8
Localidad actual 2, última localidad 9
Localidad actual 6, última localidad 2
Localidad actual 4, última localidad 6
Localidad actual 5, última localidad 4
Localidad actual 3, última localidad 5
Localidad actual 1, última localidad 3
Localidad actual 10, última localidad 1
Localidad actual 7, última localidad 10
Localidad actual 10, última localidad 10
Localidad actual 5, última localidad 10
Localidad actual 9, última localidad 5
Localidad actual 7, última localidad 9
Localidad actual 1, última localidad 7
Localidad actual 2, última localidad 1
Localidad act

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'