## Diseño aerodinámico

Existen cuatro variables que representan valores de parámetros para el diseño de el ala de una aeronave. Cada uno de estos parámetros puede tomar un valor entre 0 y 63.

El modelo aerodinámico dice que la elevación del ala está dada por la formula:

Elevación = (A - B)² + (C - D)² - (A-30)³ - (C-40)³

Encontrar los valores de parámetros que maximicen la elevación del ala.

## Codificación

- Definir como se codificará el problema
Para este problema el cromosoma estará compuesto por 4 genes cada uno de ellos representarán los valores de los parámetros del ala del aeronave

[X1 X2 X3 X4]

In [1]:
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt
 

## Adaptación

- Definir como se calculará la adaptación de un individuo
- ¿Existen estados que deben ser penalizados?

La función de adaptación será el resultado de la fórmula de elevación. Ya que se trata de maximizar el resultado. A mayor reultado mayor adaptación.


In [2]:
def adaptation_function(population):
    fitness = []
    for pop in population:
        fitness.append(
            ((pop[0] - pop[1]) ** 2) +
            ((pop[2] - pop[3]) ** 2) -
            ((pop[0] - 30) ** 3) -
            ((pop[2] - 30) ** 3)
        )
    return fitness

## Selección

In [3]:
# Recibe la lista con los entrenamientos de cada hijo y los ordena con numeros enteros ej: [1,2,3,4,5,6] basandose en el valor
# que se obtuvo en la adaptacion.
def rank(fitness,population):
    adaptation_function(population)
    array = np.array(fitness)
    temp = array.argsort()
    return (np.arange(len(array))[temp.argsort()]).tolist()
 
 
# Calculamos la probabilidad que tiene cada hijo, basandonos en la "SELECCION BASADA EN RANKING".
def probability(population, fitness):
    probability_list = []
    ranking = rank(fitness, population)
    for i in range(len(population)):
        probability_list.append(
            ((ranking[i]) / sum(ranking))
        )
    return probability_list
 
 
# Seleccionamos el/los padres de la lista de la poblacion, basandonos en la 
# probabilidad de cada individuo.
def select_parents(parents_num, population_len, probability_list):
    # population, weights = probability_list, k = parents_num
    population_aux = range(population_len)
    print(probability_list)
    parent_indexs = np.random.choice(population_aux,size=parents_num, replace=False, p=probability_list)
    return [population[i] for i in parent_indexs]



## Cruza

In [4]:
def crossover(parents):
    parents = np.array(parents)
    childrens = np.empty((len(parents),parents.shape[1]))
    crossover_point = np.uint8(parents.shape[0]/2)
    print(crossover_point)
    for k in range(len(parents)):
        # Índice del primer padre para realizar la cruza
        parent1_idx = k%parents.shape[0]
        # Índice del segundo padre para realizar la cruza
        parent2_idx = (k+1)%parents.shape[0]
        # Generar el primer hijo con la primer mitad de un padre y la segunda de otro
        childrens[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # Generar el segundo hijo con las partes opuestas
        childrens[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    #Devolver lista de hijos
    return childrens

## Mutación
#### aplicamos mutación por limite - menor.

In [5]:
def mutation(childrens):
    for i, children in enumerate(childrens):
        random_index = random.choice(range(4))
        childrens[i][random_index] = round(random.uniform(0,63), 2)
    return childrens

# Algoritmo

In [6]:
def create_population():
    population = []
    amount_population = 60

    for _ in range(amount_population):
        a = round(random.uniform(0, 63),2)
        b = round(random.uniform(0, 63),2)
        c = round(random.uniform(0, 63),2)
        d = round(random.uniform(0, 63),2)

        population.append([round(a, 2),round(b, 2),round(c, 2),round(d, 2)])
    return population
if __name__ == "__main__":
    
    population = create_population()
    population_len = len(population)
    for i in range(200):
        fitness = adaptation_function(population)
        probability_list = probability(population, fitness)
        print(probability_list)
        selected_parents = select_parents(population_len // 2, population_len, probability_list)
        print(selected_parents)
        childrens = crossover(selected_parents)
        print(childrens)
        childrens = mutation(childrens)
        print(childrens)
        selected_parents.extend(childrens.tolist())
        new_population = selected_parents
        print(new_population)
        population_len = len(new_population)
        population = new_population
    
    #Obtener la mejor solución
    fitness = cal_pop_fitness(new_population)
    best_match_idx = numpy.where(fitness == numpy.max(fitness))
    print("Mejor resultado : ", new_population[best_match_idx, :])
    print("Adaptación del mejor resultado : ", fitness[best_match_idx[0][0]])
    

[0.0062146892655367235, 0.003389830508474576, 0.0005649717514124294, 0.00847457627118644, 0.02598870056497175, 0.011299435028248588, 0.007344632768361582, 0.020903954802259886, 0.001694915254237288, 0.025423728813559324, 0.024293785310734464, 0.0022598870056497176, 0.02655367231638418, 0.01751412429378531, 0.02711864406779661, 0.010734463276836158, 0.03220338983050847, 0.0327683615819209, 0.012429378531073447, 0.00903954802259887, 0.029943502824858758, 0.023163841807909605, 0.03333333333333333, 0.023728813559322035, 0.0192090395480226, 0.02937853107344633, 0.01864406779661017, 0.021468926553672316, 0.01977401129943503, 0.0039548022598870055, 0.0096045197740113, 0.015254237288135594, 0.022598870056497175, 0.015819209039548022, 0.014124293785310734, 0.005084745762711864, 0.01807909604519774, 0.031638418079096044, 0.007909604519774011, 0.010169491525423728, 0.02768361581920904, 0.002824858757062147, 0.006779661016949152, 0.01638418079096045, 0.02824858757062147, 0.013559322033898305, 0.00

[[ 0.44 17.31  7.5  52.39]
 [11.53 45.62  5.31 41.25]
 [17.25 24.57  1.74 53.99]
 [ 0.44 58.19 20.88 47.66]
 [ 0.44 45.84  7.5  61.43]
 [ 0.44 53.28 34.81 51.78]
 [ 0.44 62.    7.5  52.39]
 [ 0.44 53.28  7.5  54.58]
 [ 0.44 47.57  7.5  61.43]
 [32.07  5.86  0.53 62.88]
 [ 0.44 53.28 34.81  3.97]
 [ 0.44 11.17  7.5  61.43]
 [ 0.44 51.32  7.5  15.04]
 [ 0.44 35.19 21.26 22.95]
 [35.39 42.81  1.74 50.62]
 [ 0.44 45.84  9.34 51.78]
 [ 0.44 53.28 32.63 51.78]
 [35.39 42.81  1.74 14.52]
 [32.07 24.17  0.53 59.4 ]
 [ 2.37 24.17  0.53 59.4 ]
 [ 0.44 35.19 10.98 52.39]
 [ 0.28 41.93 28.33 17.8 ]
 [ 0.44 16.9   7.5   5.48]
 [ 0.44 53.28 32.63 15.92]
 [13.3  24.57  1.74 53.99]
 [ 0.44 51.32  7.5  52.39]
 [ 0.44 53.28 39.97 51.78]
 [ 0.44 58.19 59.97 47.66]
 [ 4.3  53.73  7.5  14.46]
 [ 0.44 25.62 10.98 52.39]]
[[ 0.44 17.31  7.5  61.23]
 [11.53 29.69  5.31 41.25]
 [36.23 24.57  1.74 53.99]
 [ 0.44 41.02 20.88 47.66]
 [ 0.44 45.84 17.68 61.43]
 [25.04 53.28 34.81 51.78]
 [ 0.44 47.84  7.5  52.39]


[[ 0.44 57.18  7.5  36.48]
 [ 0.44 47.57  7.5  61.43]
 [ 0.44  5.04  7.5  52.39]
 [ 0.44  6.53  9.79 25.76]
 [ 0.44 54.58  7.5  52.39]
 [ 0.44  7.98  0.16 15.04]
 [ 0.44 56.94  7.5  15.04]
 [ 0.44 52.4   4.35 48.5 ]
 [ 0.44 45.84  7.5  32.32]
 [ 0.44 47.57 52.94 46.99]
 [ 0.44 61.68  9.35 61.43]
 [ 0.44 33.74  7.5  15.04]
 [17.86 34.49 10.48 61.43]
 [ 0.44 47.57  7.5  46.99]
 [ 0.44  0.23 10.48 61.43]
 [ 0.44 12.08  7.36  5.48]
 [ 0.44 47.57 10.48 61.43]
 [ 0.44 41.25  7.5   4.88]
 [ 0.44  8.99  7.5  61.43]
 [ 0.44 12.08  4.35  5.48]
 [ 0.44 47.57  7.5   9.34]
 [ 0.44 53.13  7.5  52.39]
 [ 0.44 45.84  7.5   0.4 ]
 [ 8.33 11.04  7.5  52.39]
 [ 0.44 51.32  7.5  15.04]
 [ 0.44 45.84  7.5  53.27]
 [ 0.44 61.68  7.5  61.43]
 [ 0.44  7.98  7.5  15.04]
 [ 0.44 47.57 25.4  17.02]
 [24.3  51.32  7.5  15.04]]
[[ 0.44 57.18 58.27 36.48]
 [ 0.44 47.57 47.98 61.43]
 [ 0.44  5.04 27.6  52.39]
 [ 0.44 58.84  9.79 25.76]
 [ 0.44 54.58  7.5  17.45]
 [ 0.44  7.98 29.92 15.04]
 [ 0.44 56.94  7.5  31.7 ]


[[4.400e-01 6.016e+01 7.500e+00 3.638e+01]
 [4.400e-01 7.980e+00 1.600e-01 4.215e+01]
 [4.400e-01 6.185e+01 1.600e-01 5.400e-01]
 [4.400e-01 6.016e+01 1.200e+00 4.668e+01]
 [2.400e-01 7.980e+00 1.600e-01 4.516e+01]
 [4.400e-01 5.252e+01 7.500e+00 5.872e+01]
 [4.400e-01 5.594e+01 1.600e-01 5.041e+01]
 [4.400e-01 1.750e+00 2.417e+01 3.610e+01]
 [4.400e-01 1.625e+01 7.500e+00 5.859e+01]
 [4.400e-01 1.816e+01 1.600e-01 5.119e+01]
 [4.400e-01 7.030e+00 1.600e-01 4.271e+01]
 [4.400e-01 6.016e+01 1.200e+00 3.216e+01]
 [4.400e-01 1.750e+00 7.500e+00 3.025e+01]
 [4.400e-01 5.746e+01 7.500e+00 1.867e+01]
 [4.400e-01 4.584e+01 6.060e+00 4.510e+01]
 [4.400e-01 5.694e+01 7.500e+00 1.487e+01]
 [4.400e-01 3.435e+01 1.600e-01 5.041e+01]
 [4.400e-01 4.757e+01 1.382e+01 5.199e+01]
 [4.400e-01 3.526e+01 1.600e-01 4.271e+01]
 [4.400e-01 7.760e+00 1.600e-01 5.041e+01]
 [4.400e-01 5.304e+01 1.600e-01 5.041e+01]
 [4.400e-01 2.359e+01 5.690e+00 4.510e+01]
 [4.400e-01 5.422e+01 7.500e+00 3.025e+01]
 [4.400e-01

[0.014689265536723164, 0.01694915254237288, 0.023163841807909605, 0.015254237288135594, 0.0062146892655367235, 0.030508474576271188, 0.01864406779661017, 0.03333333333333333, 0.021468926553672316, 0.0327683615819209, 0.011864406779661017, 0.0192090395480226, 0.02598870056497175, 0.031638418079096044, 0.022033898305084745, 0.010169491525423728, 0.02937853107344633, 0.010734463276836158, 0.020903954802259886, 0.00903954802259887, 0.029943502824858758, 0.012429378531073447, 0.0288135593220339, 0.013559322033898305, 0.024293785310734464, 0.024858757062146894, 0.022598870056497175, 0.015819209039548022, 0.02768361581920904, 0.01638418079096045, 0.005084745762711864, 0.005649717514124294, 0.0005649717514124294, 0.01807909604519774, 0.0, 0.00847457627118644, 0.02711864406779661, 0.03220338983050847, 0.012994350282485875, 0.0096045197740113, 0.011299435028248588, 0.023728813559322035, 0.007344632768361582, 0.0011299435028248588, 0.002824858757062147, 0.007909604519774011, 0.025423728813559324,

 [15.56 60.71  0.16 19.03]]
[[50.53 46.05  0.16 42.15]
 [ 0.44  4.49  0.16 43.21]
 [ 0.17 53.53  0.63 24.52]
 [ 0.44 48.2   0.16 36.66]
 [48.72 53.53 13.64 27.95]
 [ 0.17 60.71 25.08 55.36]
 [ 0.17 38.9   0.16 21.18]
 [ 0.17 61.18  0.16 25.13]
 [ 0.17 53.53  0.16 37.92]
 [12.11 53.7   0.16 55.36]
 [ 0.17 48.98  0.16 22.5 ]
 [ 0.17 43.99 28.86 24.16]
 [ 0.17 62.79  0.16 60.47]
 [15.88 38.9   0.16  1.42]
 [ 0.17 41.56  0.16 62.98]
 [36.31 46.78  0.16 42.15]
 [ 0.17 33.29  0.16 36.45]
 [ 0.17 50.77 20.03 58.38]
 [ 0.17 49.87  0.16 36.94]
 [20.81 50.51  0.16 19.74]
 [ 0.17 60.71 59.9  55.42]
 [ 0.17  4.74  0.16 13.12]
 [35.67 38.9   0.16 49.72]
 [ 0.17 50.51  0.16 51.82]
 [ 1.02 37.74 55.3  49.72]
 [ 0.17  4.73  0.16 58.23]
 [ 0.17 53.53  0.16 14.48]
 [46.23 14.    0.16 49.72]
 [ 0.17 56.66  0.16 28.14]
 [50.61 60.71  0.16 19.03]]
[[45.79, 46.05, 0.16, 42.15], [0.44, 4.49, 0.16, 7.65], [0.17, 53.53, 0.63, 62.98], [0.44, 48.2, 0.16, 54.83], [0.17, 53.53, 13.64, 27.95], [0.17, 60.71, 0.16, 5

[[ 0.17 34.49  0.16 46.84]
 [ 0.17 30.57  0.16 52.32]
 [ 0.17 60.6   0.16 58.38]
 [ 0.17  0.41  0.16 55.36]
 [ 0.17  8.81  0.16 42.8 ]
 [ 0.17 53.53  0.16 40.82]
 [ 0.17 62.79  0.16  7.89]
 [ 0.17 48.98  0.16 39.07]
 [ 0.17 35.71  0.16 58.38]
 [ 0.17 49.07  0.16 58.38]
 [ 0.17 30.57  0.16 21.2 ]
 [ 0.17 62.03 36.02 33.44]
 [ 0.17 59.99  0.16 40.63]
 [ 4.88 46.78  0.16  4.46]
 [ 0.17 10.48  0.16 46.84]
 [ 4.88 46.78  0.16 61.57]
 [ 0.17 13.68  0.16 55.97]
 [ 0.17 45.35  0.16 55.36]
 [ 0.17 35.31  0.16 40.82]
 [ 0.17 62.03  0.16 28.3 ]
 [ 0.17 14.43  0.16 37.1 ]
 [ 0.17 59.99  0.16 24.28]
 [ 0.17 43.23  0.16 58.38]
 [ 5.91 13.68  0.16  9.67]
 [ 0.17 52.33  0.16 40.82]
 [ 0.17 48.98  0.16 32.78]
 [ 8.75 13.67  0.16 49.57]
 [ 0.17 62.03  0.16 58.38]
 [ 0.17 59.99  0.16 33.15]
 [ 0.17 59.58  0.16 39.13]]
[[20.48 34.49  0.16 46.84]
 [ 0.17 30.57  0.16 59.82]
 [ 0.17  0.12  0.16 58.38]
 [43.52  0.41  0.16 55.36]
 [ 0.17  8.81 11.04 42.8 ]
 [ 0.17 36.79  0.16 40.82]
 [ 0.17 62.79 45.92  7.89]


[[19.92  2.82  0.16 43.8 ]
 [ 0.17 59.99  0.16 24.28]
 [ 0.17 61.79  0.16 41.84]
 [ 0.17 53.68  0.16 61.03]
 [ 0.17 36.85  0.16 39.07]
 [ 0.17 59.99  0.16 40.63]
 [ 0.17 54.51  0.16 55.36]
 [ 0.17 60.84  4.68 41.84]
 [ 0.17 48.98  0.16 39.07]
 [ 0.17 26.2  61.23 36.17]
 [ 0.17 62.22  0.16 40.82]
 [ 0.17 62.03  0.16 41.84]
 [ 4.05 62.03  0.16 41.84]
 [ 0.17  2.82  0.16 43.8 ]
 [ 0.17 26.2   0.16 36.17]
 [ 0.17 59.99  0.16 43.8 ]
 [ 0.17 11.84  0.16 24.28]
 [ 0.17 35.89  5.97 40.52]
 [27.93 36.    1.76 24.28]
 [11.15 11.84  0.16 24.28]
 [12.59 18.29  0.16 44.02]
 [10.45 52.71  0.51 58.38]
 [13.62 30.57  0.16 62.5 ]
 [ 0.17 62.22  0.16 37.41]
 [ 0.17 52.71  0.51 58.38]
 [ 5.26 37.38  0.16 39.07]
 [ 0.17 60.18  0.16 55.36]
 [10.96 60.6   0.16 20.74]
 [12.59 18.29  0.16 30.83]
 [ 0.17 15.05  0.16 19.75]]
[[1.992e+01 4.369e+01 1.600e-01 4.380e+01]
 [1.700e-01 5.999e+01 1.600e-01 5.391e+01]
 [1.700e-01 3.625e+01 1.600e-01 4.184e+01]
 [1.700e-01 3.647e+01 1.600e-01 6.103e+01]
 [1.700e-01 3.685

[[ 0.28 47.65  0.16 25.86]
 [ 0.17 59.99  0.16 59.05]
 [ 0.17  6.83  0.16 52.26]
 [ 0.17 47.65  0.16  8.18]
 [ 0.17 36.47  0.16 34.12]
 [ 0.17 41.61  0.16 61.03]
 [ 0.17  3.42  0.16 23.14]
 [ 0.17 50.97  0.16 52.26]
 [ 0.17 18.91 10.88 25.83]
 [ 0.17 59.99 24.07 59.05]
 [ 0.17 59.99  0.16 26.93]
 [ 0.17 25.07  0.16 25.83]
 [ 0.17 54.26  0.16 61.03]
 [33.24 58.04  0.16 53.91]
 [ 0.17  5.46  0.16 61.03]
 [ 0.17 12.09  0.16 40.63]
 [ 0.17 61.79 19.41 41.84]
 [ 0.17 36.47  0.16  8.64]
 [ 0.17 47.65  0.16 61.03]
 [ 0.17 18.91  0.16 52.75]
 [ 0.17 19.54  0.16 25.83]
 [ 0.17 56.    0.16 61.03]
 [ 0.17 50.97  0.16 53.94]
 [ 0.17 47.65  0.16 25.86]
 [ 0.17 53.53 31.01  8.64]
 [ 0.17  5.46  0.16 46.45]
 [ 0.17 10.59  0.16 19.78]
 [ 0.17  3.42  0.16 58.98]
 [ 4.74 36.47  0.16  8.64]
 [ 0.17 18.91  0.16 25.83]]
[[ 0.28 47.65  0.16 56.21]
 [ 0.17 59.99  0.16 55.24]
 [ 0.17 20.3   0.16 52.26]
 [32.48 47.65  0.16  8.18]
 [ 0.17 36.47  0.16 33.57]
 [ 0.17 41.61  0.16 17.12]
 [ 0.17 55.67  0.16 23.14]


[[ 0.17 19.54  0.16 53.29]
 [ 0.17 59.99  0.16 29.62]
 [ 0.17 54.26  0.16 13.69]
 [ 0.17 50.97  0.16 45.5 ]
 [ 0.17 25.32  0.16 61.03]
 [ 0.17 15.81  0.16 45.71]
 [ 0.17 38.04  0.16 52.75]
 [ 0.17 59.39  0.16 61.03]
 [ 0.17 42.21  0.37 55.24]
 [ 0.17 50.97  0.16 53.94]
 [ 0.17 27.78  0.16 61.03]
 [ 0.17  5.46  0.16 19.29]
 [ 0.17 50.75  0.16  8.31]
 [ 0.17 45.59  0.16 52.75]
 [ 0.17 39.29  0.16 52.75]
 [ 0.17 59.12  0.16 61.03]
 [ 0.17 18.91  0.16 52.75]
 [ 0.17 59.99  0.16  5.84]
 [ 4.77 59.99  0.16 26.93]
 [ 0.17 25.32  0.16 59.18]
 [ 0.17 25.32  2.97 23.18]
 [ 0.17 57.57  0.16 61.03]
 [ 0.17 12.09  2.3  40.63]
 [ 0.17  9.54  0.16 15.36]
 [ 0.17 59.99  0.16 45.71]
 [ 0.17 27.18  0.16 61.03]
 [ 0.17 22.75  0.16 61.03]
 [42.54  1.47  0.16 53.94]
 [ 0.17 50.97  0.16 59.47]
 [ 0.17 54.64  0.16 61.03]]
[[ 0.17 26.54  0.16 53.29]
 [18.58 59.99  0.16 29.62]
 [ 0.17 54.26  0.16 41.87]
 [ 0.17 50.97 17.98 45.5 ]
 [34.69 25.32  0.16 61.03]
 [ 0.17 39.17  0.16 45.71]
 [ 0.17 38.04  0.16 11.29]


 [ 0.17 29.18  0.16 35.16]]
[[ 0.17 55.34  0.16 53.97]
 [13.76 59.39 27.11 61.03]
 [ 0.17 20.56  2.18 53.97]
 [ 0.33 42.67  8.74 43.58]
 [ 0.33 18.86  0.16 46.05]
 [61.46 10.46  0.16 49.31]
 [ 0.17 17.19  0.16 24.2 ]
 [ 0.17 46.26  0.16 53.97]
 [55.15 56.77  0.16 41.73]
 [ 0.17 29.18  0.16  8.93]
 [32.77 45.59  0.16 53.97]
 [35.31 16.07 14.99 59.47]
 [ 0.33 42.67  2.88 30.27]
 [38.66 19.64  0.16 53.97]
 [ 0.17 49.73 36.32 21.65]
 [33.79  1.77  0.16 50.31]
 [ 0.17 20.63 29.45 60.58]
 [ 0.33  4.54  0.16 60.65]
 [ 0.17 43.95  0.16  3.81]
 [19.58 17.19  0.16 61.7 ]
 [ 0.33 59.39  0.16 38.08]
 [ 0.75 56.77  0.16 36.09]
 [ 0.33 51.97  0.16 61.03]
 [ 0.33 59.39 52.53 31.73]
 [ 0.17 47.66  0.16 60.58]
 [39.85 14.48  3.26 50.76]
 [ 1.17 56.77  0.16 36.09]
 [ 0.33 42.67 60.23 43.58]
 [ 0.17 22.75  0.16 30.02]
 [ 0.17 29.18  9.37 35.16]]
[[0.17, 49.73, 0.16, 53.97], [13.76, 59.39, 27.36, 61.03], [0.17, 20.56, 0.16, 53.97], [0.33, 42.67, 51.9, 43.58], [0.33, 25.34, 0.16, 46.05], [0.17, 10.46, 0.16

[[ 0.17  4.93 33.6  17.7 ]
 [ 0.33 52.14  0.16  5.02]
 [60.55 62.58 32.51 56.29]
 [ 0.17 11.92  0.67  9.59]
 [10.21 20.63  0.16 58.75]
 [17.79 15.1   0.16 43.04]
 [29.7  25.34  0.16 46.05]
 [59.88 15.1   0.16 61.6 ]
 [ 0.17 34.87  0.16 61.77]
 [ 0.33 29.92  0.16 47.28]
 [18.64 42.67  2.88 30.27]
 [ 0.33 62.11 54.77 46.05]
 [ 0.75 40.36  0.16 37.89]
 [ 0.33 19.31  0.16 20.21]
 [ 8.8  56.77 19.89 56.29]
 [ 0.17 17.19  0.16 19.67]
 [21.12 56.77  0.16 56.29]
 [ 2.15 20.63 28.4  58.75]
 [ 0.33 59.39  0.16  9.88]
 [58.81 59.39  0.16 47.28]
 [11.14 62.11  0.16 46.05]
 [ 0.17 45.65  0.16 53.97]
 [ 0.17 33.35  0.16 53.97]
 [ 0.75 32.78  0.16 30.23]
 [13.87 57.24  0.16 46.05]
 [ 0.33 42.67  1.   30.27]
 [ 9.62 59.39  0.16 38.08]
 [53.39 49.73 20.8  53.97]
 [ 1.67  4.27  0.16 29.4 ]
 [ 0.17 39.17 62.28 53.97]]
[[0.17, 4.93, 0.16, 17.7], [0.33, 52.14, 0.16, 38.08], [0.17, 62.58, 32.51, 56.29], [0.17, 47.66, 0.67, 9.59], [0.17, 20.63, 0.16, 58.75], [17.79, 15.1, 0.16, 61.6], [0.33, 25.34, 0.16, 46.

[[ 0.17 58.87 14.57 35.31]
 [ 0.17 53.67  5.71 43.72]
 [ 0.17 17.19  6.69 19.26]
 [ 0.17 51.52  0.16 53.97]
 [ 0.17 39.17  0.16 61.77]
 [ 0.17 30.41  6.69 19.26]
 [ 0.17 20.63  0.16 58.75]
 [ 0.33 13.14  0.16 38.08]
 [ 0.17 27.67  0.16 58.75]
 [ 0.33 15.1   0.16 54.55]
 [ 0.17 35.87  0.16 45.34]
 [14.76 27.67  0.16 58.75]
 [ 0.17  9.44  0.16 48.73]
 [ 0.17 59.12  0.16 20.23]
 [13.68 56.01  0.16 25.58]
 [ 0.17 59.12 37.89 20.23]
 [ 0.33 54.11  0.16 38.08]
 [ 0.33 59.39  0.16 38.08]
 [ 0.17 52.81  0.16 61.25]
 [ 0.17  7.06  0.16 48.73]
 [ 0.17 20.63  0.16 48.73]
 [ 0.17 52.81  0.16 51.39]
 [ 0.17 17.19  6.69 19.67]
 [ 0.33 59.39  0.16 20.04]
 [ 0.85 17.19  6.69 33.78]
 [ 0.17 52.81 46.49 23.1 ]
 [ 0.17 55.34  0.16 45.34]
 [ 0.17 11.42 14.57 35.31]
 [ 6.25 15.1   2.61 61.6 ]
 [ 6.25 15.1   0.16 61.6 ]]
[[ 0.17 58.87 58.94 35.31]
 [ 0.17 53.67  5.71 46.78]
 [24.17 17.19  6.69 19.26]
 [ 0.17 51.52 56.36 53.97]
 [ 0.17 39.17  0.16 30.4 ]
 [30.55 30.41  6.69 19.26]
 [ 0.17 40.73  0.16 58.75]


[0.014689265536723164, 0.0327683615819209, 0.029943502824858758, 0.021468926553672316, 0.025423728813559324, 0.02768361581920904, 0.02937853107344633, 0.01807909604519774, 0.011864406779661017, 0.01638418079096045, 0.0192090395480226, 0.031638418079096044, 0.02598870056497175, 0.01864406779661017, 0.022598870056497175, 0.031073446327683617, 0.0288135593220339, 0.015819209039548022, 0.0039548022598870055, 0.030508474576271188, 0.001694915254237288, 0.02824858757062147, 0.024858757062146894, 0.01977401129943503, 0.02655367231638418, 0.015254237288135594, 0.020338983050847456, 0.011299435028248588, 0.01694915254237288, 0.010169491525423728, 0.014124293785310734, 0.00903954802259887, 0.003389830508474576, 0.007909604519774011, 0.03220338983050847, 0.023163841807909605, 0.013559322033898305, 0.007344632768361582, 0.012429378531073447, 0.005649717514124294, 0.024293785310734464, 0.006779661016949152, 0.022033898305084745, 0.023728813559322035, 0.005084745762711864, 0.03333333333333333, 0.020

 [ 7.78 54.4  44.7   1.28]]
[[0.17, 55.34, 20.18, 39.2], [0.17, 31.04, 0.16, 50.5], [0.17, 2.16, 0.16, 46.62], [0.17, 40.17, 0.16, 52.56], [0.17, 51.52, 0.16, 30.97], [0.17, 48.94, 0.16, 30.35], [0.17, 51.52, 0.16, 1.28], [0.17, 35.51, 3.51, 37.61], [12.31, 50.21, 0.16, 27.37], [0.17, 35.51, 0.16, 46.62], [5.02, 58.65, 0.16, 58.36], [0.17, 36.73, 0.16, 1.28], [0.17, 54.4, 0.16, 1.28], [0.17, 55.34, 20.18, 10.57], [0.17, 40.93, 0.16, 46.62], [0.17, 32.31, 0.16, 56.31], [0.17, 35.51, 3.51, 46.62], [0.17, 51.52, 0.16, 30.41], [0.17, 53.35, 0.16, 21.66], [0.17, 60.62, 0.16, 56.31], [0.17, 60.62, 0.16, 13.94], [0.17, 22.9, 0.16, 39.2], [0.17, 31.04, 0.16, 46.62], [12.31, 10.3, 0.16, 27.37], [0.17, 55.34, 35.55, 10.57], [0.17, 59.67, 12.65, 27.37], [14.08, 47.22, 0.16, 34.68], [0.17, 10.66, 31.62, 62.21], [0.17, 51.52, 0.16, 56.63], [7.78, 54.4, 0.16, 1.28], [0.17, 55.34, 20.18, 3.91], [0.17, 31.04, 51.12, 50.5], [0.17, 2.16, 0.16, 29.4], [18.54, 40.17, 0.16, 52.56], [0.17, 51.52, 0.16, 1.47

[[1.700e-01 1.330e+01 1.600e-01 6.003e+01]
 [2.280e+01 3.790e+01 1.600e-01 2.077e+01]
 [1.700e-01 2.911e+01 2.286e+01 3.393e+01]
 [1.700e-01 2.290e+01 5.261e+01 8.200e-01]
 [1.700e-01 4.017e+01 1.600e-01 5.413e+01]
 [1.700e-01 1.649e+01 2.448e+01 1.280e+00]
 [1.700e-01 6.168e+01 1.600e-01 4.662e+01]
 [6.061e+01 2.069e+01 1.600e-01 5.050e+01]
 [1.700e-01 2.082e+01 7.100e-01 1.280e+00]
 [5.479e+01 1.932e+01 1.600e-01 4.841e+01]
 [1.700e-01 2.953e+01 1.600e-01 2.562e+01]
 [4.833e+01 5.921e+01 1.600e-01 5.663e+01]
 [1.700e-01 3.112e+01 1.600e-01 5.227e+01]
 [1.700e-01 2.290e+01 1.600e-01 3.198e+01]
 [1.700e-01 5.479e+01 1.600e-01 5.521e+01]
 [1.700e-01 2.965e+01 1.600e-01 1.092e+01]
 [3.830e+00 3.551e+01 8.200e+00 1.092e+01]
 [1.700e-01 3.112e+01 5.405e+01 4.636e+01]
 [1.700e-01 2.152e+01 1.600e-01 3.829e+01]
 [1.700e-01 5.098e+01 6.500e-01 2.166e+01]
 [1.700e-01 1.733e+01 3.510e+00 5.477e+01]
 [5.166e+01 3.112e+01 3.000e-02 5.050e+01]
 [2.456e+01 2.911e+01 1.600e-01 3.393e+01]
 [1.820e+01

[0.031638418079096044, 0.02768361581920904, 0.01864406779661017, 0.02598870056497175, 0.030508474576271188, 0.023163841807909605, 0.024858757062146894, 0.014124293785310734, 0.01638418079096045, 0.023728813559322035, 0.022598870056497175, 0.031073446327683617, 0.013559322033898305, 0.021468926553672316, 0.01751412429378531, 0.00847457627118644, 0.015254237288135594, 0.02711864406779661, 0.0288135593220339, 0.02937853107344633, 0.03220338983050847, 0.01807909604519774, 0.020903954802259886, 0.012994350282485875, 0.029943502824858758, 0.025423728813559324, 0.02655367231638418, 0.020338983050847456, 0.0327683615819209, 0.0096045197740113, 0.001694915254237288, 0.0011299435028248588, 0.0005649717514124294, 0.010734463276836158, 0.007909604519774011, 0.03333333333333333, 0.011864406779661017, 0.002824858757062147, 0.01977401129943503, 0.005649717514124294, 0.007344632768361582, 0.006779661016949152, 0.00903954802259887, 0.003389830508474576, 0.024293785310734464, 0.0, 0.015819209039548022, 

15
[[ 0.17 41.97  0.16 60.73]
 [ 0.17 41.97  0.16 60.88]
 [ 0.17 52.35  0.16 61.94]
 [ 0.17 60.88  2.77  9.9 ]
 [ 0.17 62.25  0.16 32.66]
 [ 0.17 58.93  0.16 55.98]
 [ 0.17 59.1   0.16 61.94]
 [ 0.17 52.35  0.16 49.28]
 [24.62 58.93  0.16 55.98]
 [ 0.17 62.44  0.16 61.94]
 [ 0.17 31.87  0.16 38.63]
 [ 0.17 52.35  0.16 17.09]
 [ 0.17 27.8  11.49 61.94]
 [ 0.17 27.8   0.16 61.94]
 [ 0.17 12.9   0.16 61.94]
 [ 0.17 58.93  0.16 28.27]
 [ 0.17 24.01  0.16 61.94]
 [ 0.17 53.14  0.16 58.65]
 [ 0.17 52.35 13.69 40.66]
 [ 0.17 52.35  0.16 32.66]
 [ 0.17 59.15  0.16 10.92]
 [23.52 31.87  0.16 38.63]
 [ 0.17 51.35  0.16 61.94]
 [ 0.17 60.88  0.16  9.9 ]
 [14.81 52.35  0.16 61.94]
 [ 0.17 21.09  1.67 49.99]
 [ 0.17 52.35 13.69 61.94]
 [ 0.17 15.65  0.16  1.94]
 [ 0.17 52.99  0.16 62.98]
 [ 0.17 60.62 59.89 38.29]]
[[ 0.17 62.17  0.16 60.73]
 [ 0.17 41.97  0.16 33.05]
 [ 0.17 52.35  0.16 13.86]
 [ 0.17 60.88  2.77 57.49]
 [ 0.17 41.93  0.16 32.66]
 [ 0.17 58.93  0.16  2.77]
 [ 0.17 59.1   0.16  4.9

[[1.700e-01 6.244e+01 1.600e-01 6.194e+01]
 [5.000e-02 2.401e+01 1.600e-01 1.517e+01]
 [1.700e-01 6.217e+01 1.600e-01 6.073e+01]
 [1.700e-01 6.225e+01 1.600e-01 7.700e-01]
 [1.700e-01 6.289e+01 1.600e-01 9.180e+00]
 [1.700e-01 5.135e+01 1.600e-01 6.194e+01]
 [1.700e-01 4.398e+01 1.600e-01 3.261e+01]
 [1.700e-01 5.970e+01 1.600e-01 3.013e+01]
 [1.700e-01 5.235e+01 1.600e-01 3.178e+01]
 [1.700e-01 2.667e+01 1.600e-01 3.266e+01]
 [1.700e-01 5.235e+01 1.600e-01 2.617e+01]
 [1.700e-01 5.061e+01 1.600e-01 5.545e+01]
 [1.700e-01 4.398e+01 1.690e+00 3.261e+01]
 [1.700e-01 1.265e+01 1.600e-01 6.194e+01]
 [1.700e-01 6.217e+01 1.600e-01 3.013e+01]
 [1.700e-01 6.244e+01 3.694e+01 6.194e+01]
 [1.700e-01 6.225e+01 1.600e-01 3.266e+01]
 [1.700e-01 5.235e+01 1.600e-01 4.559e+01]
 [1.700e-01 5.235e+01 1.600e-01 1.915e+01]
 [1.700e-01 5.061e+01 1.600e-01 5.865e+01]
 [4.500e-01 5.061e+01 1.600e-01 5.865e+01]
 [5.000e-02 2.401e+01 1.600e-01 6.194e+01]
 [1.700e-01 5.186e+01 1.600e-01 6.194e+01]
 [3.582e+01

[[1.700e-01 7.360e+00 1.600e-01 3.266e+01]
 [1.700e-01 6.174e+01 1.600e-01 1.306e+01]
 [1.700e-01 1.189e+01 1.302e+01 5.683e+01]
 [1.700e-01 2.910e+01 5.270e+00 3.013e+01]
 [1.700e-01 4.428e+01 1.600e-01 3.539e+01]
 [1.700e-01 2.790e+01 1.605e+01 6.194e+01]
 [5.000e-02 4.166e+01 1.600e-01 6.194e+01]
 [5.000e-02 4.166e+01 1.600e-01 4.366e+01]
 [2.485e+01 3.530e+01 1.600e-01 6.194e+01]
 [3.220e+01 2.090e+01 1.600e-01 5.683e+01]
 [1.700e-01 5.760e+01 1.600e-01 3.433e+01]
 [1.700e-01 1.265e+01 1.600e-01 4.913e+01]
 [1.700e-01 5.482e+01 1.600e-01 9.900e+00]
 [1.700e-01 5.760e+01 2.100e-01 3.433e+01]
 [1.700e-01 5.200e+01 1.600e-01 5.552e+01]
 [1.700e-01 3.530e+01 1.600e-01 6.194e+01]
 [2.512e+01 3.251e+01 1.600e-01 6.194e+01]
 [1.700e-01 4.686e+01 2.880e+00 4.203e+01]
 [1.700e-01 6.174e+01 1.600e-01 8.330e+00]
 [1.700e-01 5.760e+01 1.600e-01 5.649e+01]
 [1.700e-01 4.686e+01 2.880e+00 6.194e+01]
 [1.700e-01 3.960e+01 1.600e-01 6.194e+01]
 [3.220e+01 4.428e+01 1.600e-01 5.683e+01]
 [1.700e-01

[[ 0.17 61.74  0.91 13.06]
 [ 0.17 30.19  0.16 61.94]
 [ 0.17  6.27  0.16 55.52]
 [ 0.17 61.74  0.16 13.06]
 [26.86 56.12  0.16 56.49]
 [ 1.91 29.74  0.16  8.88]
 [ 0.17 15.06  5.27 45.  ]
 [ 1.22 34.04  0.16 56.49]
 [ 0.17 53.28  0.16 55.13]
 [ 0.17 15.06  5.27 44.02]
 [ 0.17 28.59  0.16 49.13]
 [ 0.17 57.6   0.21 60.46]
 [ 0.17 57.6   0.16 56.49]
 [ 0.17 30.19  0.16 46.49]
 [ 0.17 37.53  0.16 13.06]
 [ 0.17 57.6   3.84 60.46]
 [ 0.17 60.36  0.16 43.22]
 [ 0.17 35.3   0.16  8.47]
 [ 0.17 57.6   0.21 62.78]
 [ 0.17 57.6   0.21 50.04]
 [ 5.54  7.69  0.16  9.9 ]
 [ 0.17  5.18  0.16 13.  ]
 [ 0.17 60.36  0.16  7.49]
 [ 0.17 36.67  0.16 55.52]
 [ 0.17 27.21  0.16 55.52]
 [ 0.17 57.6   0.16 52.3 ]
 [ 0.17 57.6   0.16 15.23]
 [ 0.17 27.21  0.16 47.79]
 [ 0.17 44.28  0.16 28.7 ]
 [ 0.17  3.7   0.16 49.13]]
[[ 0.17 24.6   0.91 13.06]
 [ 0.17 30.19  0.16 13.04]
 [49.41  6.27  0.16 55.52]
 [ 0.17 61.74  0.16 15.7 ]
 [62.86 56.12  0.16 56.49]
 [ 1.91  1.65  0.16  8.88]
 [27.38 15.06  5.27 45.  ]


NameError: name 'cal_pop_fitness' is not defined