## Problema del viajante

Resolver el problema del viajante utilizando algoritmos genéticos. 

- ¿Es posible aproximarse al resultado?



### Codificación

- Definir como se codificará el problema


#### Matriz de costos

##### Distancias desde San Rafael

<table>
 <tbody>
  <tr>
   <td></td>
   <td>San Rafael</td>
   <td>El Nihuil</td>
   <td>El sosneado</td>
   <td>Villa Atuel</td>
   <td>Jaime Prats</td>
   <td>Las Malvinas</td>
   <td>Salto de las Rosas</td>
   <td>Rama Caida</td>
   <td>Monte Coman</td>
   <td>Gral. Alvear</td>
   <td>Rincón del Atuel</td>
  </tr>
  <tr>
   <td>San Rafael</td>
   <td>0</td>
   <td>72.7</td>
   <td>137</td>
   <td>55</td>
   <td>74.3</td>
   <td>36.6</td>
   <td>23</td>
   <td>8.7</td>
   <td>54.2</td>
   <td>88.9</td>
   <td>37.6</td>
  </tr>
 </tbody>
</table>

##### Distancias desde otros distritos

<table>
 <tbody>
  <tr>
   <td></td>
   <td>San Rafael</td>
   <td>El Nihuil</td>
   <td>El sosneado</td>
   <td>Villa Atuel</td>
   <td>Jaime Prats</td>
   <td>Las Malvinas</td>
   <td>Salto de las Rosas</td>
   <td>Rama Caida</td>
   <td>Monte Coman</td>
   <td>Gral. Alvear</td>
   <td>Rincón del Atuel</td>
  </tr>
  <tr>
   <td>El Nihuil</td>
   <td>72.5</td>
   <td>0</td>
   <td>108</td>
   <td>120</td>
   <td>135</td>
   <td>97.4</td>
   <td>84</td>
   <td>69.7</td>
   <td>122</td>
   <td>150</td>
   <td>35</td>
  </tr>
  <tr>
   <td>El Sosneado</td>
   <td>137</td>
   <td>108</td>
   <td>0</td>
   <td>184</td>
   <td>199</td>
   <td>162</td>
   <td>148</td>
   <td>134</td>
   <td>186</td>
   <td>214</td>
   <td>99.1</td>
  </tr>
  <tr>
   <td>Villa Atuel</td>
   <td>54.3</td>
   <td>120</td>
   <td>184</td>
   <td>0</td>
   <td>16.7</td>
   <td>45.2</td>
   <td>35.6</td>
   <td>54.5</td>
   <td>47.1</td>
   <td>31.5</td>
   <td>84.7</td>
  </tr>
  <tr>
   <td>Jaime Prats</td>
   <td>70</td>
   <td>136</td>
   <td>200</td>
   <td>16.9</td>
   <td>0</td>
   <td>60.8</td>
   <td>51.3</td>
   <td>70.2</td>
   <td>41.2</td>
   <td>15</td>
   <td>100</td>
  </tr>
  <tr>
   <td>Las Malvinas</td>
   <td>36.6</td>
   <td>97.4</td>
   <td>162</td>
   <td>45.2</td>
   <td>60.8</td>
   <td>0</td>
   <td>18.8</td>
   <td>29.7</td>
   <td>57.8</td>
   <td>75.4</td>
   <td>62.6</td>
  </tr>
  <tr>
   <td>Salto de las Rosas</td>
   <td>23</td>
   <td>84</td>
   <td>148</td>
   <td>35.6</td>
   <td>51.3</td>
   <td>18.8</td>
   <td>0</td>
   <td>18.9</td>
   <td>43</td>
   <td>65.8</td>
   <td>49.1</td>
  </tr>
  <tr>
   <td>Rama Caida</td>
   <td>8.7</td>
   <td>68.7</td>
   <td>134</td>
   <td>54.5</td>
   <td>70.2</td>
   <td>29.2</td>
   <td>18.9</td>
   <td>0</td>
   <td>56.4</td>
   <td>84.7</td>
   <td>34.7</td>
  </tr>
  <tr>
   <td>Monte Coman</td>
   <td>54.2</td>
   <td>122</td>
   <td>186</td>
   <td>47.1</td>
   <td>41.2</td>
   <td>57.8</td>
   <td>43</td>
   <td>56.4</td>
   <td>0</td>
   <td>48</td>
   <td>86.5</td>
  </tr>
  <tr>
   <td>Gral. Alvear</td>
   <td>88.9</td>
   <td>150</td>
   <td>214</td>
   <td>31.5</td>
   <td>15</td>
   <td>75.4</td>
   <td>65.8</td>
   <td>84.7</td>
   <td>48</td>
   <td>0</td>
   <td>115</td>

  </tr>
  <tr>
   <td>Rincón del Atuel</td>
   <td>37.6</td>
   <td>35</td>
   <td>99.1</td>
   <td>84.7</td>
   <td>100</td>
   <td>62.6</td>
   <td>49.1</td>
   <td>34.7</td>
   <td>86.5</td>
   <td>115</td>
   <td>0</td>
  </tr>
 </tbody>
</table>

### Adaptación

- Definir como se calculará la adaptación de un individuo
- ¿Existen estados que deben ser penalizados?


## Resolución

### Objetivo

Recordemos que el objetivo del problema es, dada una lista de ciudades y las distancias entre cada par de ellas, encontrar cuál es la <strong>ruta más corta</strong> posible que visita cada ciudad exactamente una vez y que, al finalizar, regresa a la ciudad origen.

In [3]:
import numpy, random, copy, sys

numpy.set_printoptions(threshold=sys.maxsize)

In [5]:
costos = [[0,72.7,136.7,59.1,70.1,36.4,23,8.7,54.2,85.7,37.7],
              [72.7,0,107.8,120.1,135.2,97.7,84.2,69.8,122,150,35],
              [136.7,107.8,0,184,199,162,148,134,186,214,99.1],
              [59.1,120.1,184,0,16.7,45.2,35.6,54.5,47.1,31.4,84.7],
              [70.1, 135.2, 199, 16.7, 0, 60.8, 51.3, 70.2, 41.2, 15, 100],
              [36.4, 97.7, 162, 45.2, 60.8, 0, 18.8, 29.7, 57.8, 75.4, 62.6],
              [23,84.2,148,35.6,51.3,18.8,0,18.9,43,65.8,49.1],
              [8.7,69.8,134,54.5,70.2,29.7,18.9,0,56.4,84.7,34.7],
              [54.2,122,186,47.1,41.2,57.8,43,56.4,0,48,86.5],
              [85.7,150,214,31.4,15,75.4,65.8,84.7,48,0,115],
              [37.6,35,99.1,84.7,100,62.6,49.1,34.7,86.5,115,0]]

costos = numpy.array(costos)
print("Array costos de distancias: \n")
print(costos)


Array costos de distancias: 

[[  0.   72.7 136.7  59.1  70.1  36.4  23.    8.7  54.2  85.7  37.7]
 [ 72.7   0.  107.8 120.1 135.2  97.7  84.2  69.8 122.  150.   35. ]
 [136.7 107.8   0.  184.  199.  162.  148.  134.  186.  214.   99.1]
 [ 59.1 120.1 184.    0.   16.7  45.2  35.6  54.5  47.1  31.4  84.7]
 [ 70.1 135.2 199.   16.7   0.   60.8  51.3  70.2  41.2  15.  100. ]
 [ 36.4  97.7 162.   45.2  60.8   0.   18.8  29.7  57.8  75.4  62.6]
 [ 23.   84.2 148.   35.6  51.3  18.8   0.   18.9  43.   65.8  49.1]
 [  8.7  69.8 134.   54.5  70.2  29.7  18.9   0.   56.4  84.7  34.7]
 [ 54.2 122.  186.   47.1  41.2  57.8  43.   56.4   0.   48.   86.5]
 [ 85.7 150.  214.   31.4  15.   75.4  65.8  84.7  48.    0.  115. ]
 [ 37.6  35.   99.1  84.7 100.   62.6  49.1  34.7  86.5 115.    0. ]]


### Valores de costos

In [6]:
def obtener_costo_individuo(individuo_ruta):
    
    print(individuo_ruta)
    input()
    
    ultima_localidad = individuo_ruta[0]
    costo_ruta = 0
    
    for localidad_actual in individuo_ruta:
        print(f"Localidad actual {localidad_actual}, última localidad {ultima_localidad}")
        costo_ruta += costos[ultima_localidad][localidad_actual]
        ultima_localidad = localidad_actual

    # The high cost value means low fitness. Thus we
    # cannot use the cost value directly as a fitness value.
    # One can use various methods to calculate fitness values
    # from cost values.

In [ ]:
# Función de adecuacion - fitness function 
def calcular_adecuacion_cromosoma(poblacion):
    adecuacion = []
    for individuo_ruta in poblacion:
        adecuacion.append(obtener_costo_individuo(individuo_ruta))
    return adecuacion

### 1 - Codificación

Para este problema, los individuos (rutas aleatorizadas) estarán compuestos por 10 genes donde cada uno de ellos representará el valor del indice de una localidad en la lista "costos". El mismo será utilizado para trabajar los costos de cada uno de los individuos.

### 2 - Creamos la poblacion inicial

In [7]:
# Elaboramos cromosomas que seran aleatorizados para generar los individuos
crom_ejemplo = list(range(1,11))

poblacion_inicial = [ ]
random.seed(0)
tam_poblacion = 10000

for i in range(tam_poblacion):
    crom_nuevo = copy.copy(crom_ejemplo)
    random.shuffle(crom_nuevo)
    poblacion_inicial.append(crom_nuevo)

poblacion_inicial = numpy.array(poblacion_inicial)

print("\nArray población inicial: ")
print(poblacion_inicial)



Array población inicial: 
[[ 8  9  2  6  4  5  3  1 10  7]
 [10  5  9  7  1  2  8  3  4  6]
 [ 8  1 10  4  3  6  7  9  2  5]
 [ 1  3  9  4  2  8  5 10  7  6]
 [ 5  2  3  7  4  6  8 10  9  1]
 [ 9  3  7  5  2  1  8 10  4  6]
 [ 6 10  7  4  5  3  1  2  8  9]
 [ 1  4  6  8  7  3 10  2  5  9]
 [ 6  4  1 10  9  5  3  7  2  8]
 [ 7 10  8  2  6  9  4  5  1  3]
 [10  1  4  3  5  6  8  7  9  2]
 [ 8  6  2  1  3  9 10  5  7  4]
 [ 7 10  5  9  3  1  2  4  6  8]
 [ 7  5  9  2  8  1  4 10  3  6]
 [ 3  4  5  6  8  7 10  2  9  1]
 [ 4 10  3  7  9  8  5  1  2  6]
 [ 2  7  3  9  5 10  6  1  4  8]
 [ 8  7  9 10  3  6  1  4  2  5]
 [ 3  2  6  4  7  5 10  8  9  1]
 [ 5  4  9  1  2  7 10  3  8  6]
 [10  9  7  2  4  8  1  5  6  3]
 [ 2  8  1 10  4  3  6  5  9  7]
 [ 9  4  7  3  5  1 10  6  2  8]
 [ 1  4  7  2 10  3  9  5  6  8]
 [ 6  4  9  3  8  5  1  2 10  7]
 [ 3  2  1 10  5  9  6  7  8  4]
 [ 9  5  6  3  8  4  2  1  7 10]
 [ 4  3  2  6  1  7  5 10  9  8]
 [10  6  3  9  2  4  7  1  8  5]
 [ 5  4  8  6  2

## Selección

## Cruza

## Mutación

# Algoritmo