# Diabetes
Este conjunto de datos contiene diez variables base para 442 pacientes con diabetes:
- edad
- sexo
- índice de masa corporal
- presión arterial promedio 
- seis mediciones del suero sanguíneo
- respuesta de interés, una medida cuantitativa de la progresión de la enfermedad en un año.

Obtener el árbol de decisión óptimo para predecir la respuesta de interes a partir de los datos de los pacientes.

In [2]:
from sklearn import metrics
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_diabetes
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_graphviz
from IPython.display import Image
from io import StringIO
import pandas as pd
import numpy as np

import pydotplus

In [4]:
df = pd.read_csv("data/diabetes.csv")
data = df.values[:,:3]
data_columns = list(df.columns.values[:3])
target=df.values[:,3]
data
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=1)
print(X_train)


[[ 15. 136.  70.]
 [  0.  97.  64.]
 [  1. 116.  70.]
 ...
 [ 13. 126.  90.]
 [  4. 171.  72.]
 [  9. 102.  76.]]


In [7]:
reg = DecisionTreeRegressor(max_depth=4)
# Valores de entrenamiento
reg = reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)

## Valores de error y varianza

Comparamos los valores del EMC y la varianza comparando los conjuntos de prediccion y de prueba

- Si la variancia es cercana a 0.0 significa que no ha habido una prediccion, los conjuntos no están correlacionados. 
- Si la varianza es cercana a 1.0 significa que hay una prediccion perfecta.

In [8]:
mse = metrics.mean_squared_error(y_test, y_pred)
print("Error medio cuadrado: ", mse)

r2 = metrics.r2_score(y_test, y_pred)
print("Puntaje de varianza: ", r2)

Error medio cuadrado:  256.69602445086997
Puntaje de varianza:  -0.04179868134370612


In [10]:
data_columns = df.columns

In [11]:
dot_data = StringIO()
export_graphviz(reg, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = data_columns)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

ValueError: Length of feature_names, 9 does not match number of features, 3

<h3>¿Cuáles son los atributos más importantes que consideró el arbol de regresión según el EMC?</h3>
El arbol de regresión toma como atributos importantes: Índice de masa (bmi), Edad, Presión arterial promedio y Mediciones en suero sanguíneo.

<h3>¿En qué casos se tuvo un buen desempeño con respecto al avance de la enfermedad?</h3>
Consideramos un buen desempeño cuando:
<ul>
	<li>El indice de masa corporal es menor o igual a 0.01</li>
	<li>el nivel de triglicéridos es menor a 0</li>
	<li>La edad es menor o igual a 0.029</li>
</ul>
    
<h3>¿Cumple con su función este arbol de decisión?</h3>
<p>Este árbol no permite realizar predicciones sobre valores reales, teniendo en cuenta el el modelo de entrenamiento. Si permite interpretar que atributos influyen.</p>

    
